// frontend/src/app/features/auth/register.component.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { AuthService } from './auth.service';

export const RegisterComponent = () => {
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    const initGoogle = () => {
      if (window.google) {
        window.google.accounts.id.initialize({
          client_id: '725051219392-u8oac67c5dusdgb9ht9q3u683iss1lfl.apps.googleusercontent.com',
          callback: (res: any) => handleGoogleLogin(res.credential),
        });
        window.google.accounts.id.renderButton(
          document.getElementById('googleBtnReg'),
          { theme: 'outline', size: 'large', width: 350 }
        );
      }
    };

    const script = document.createElement('script');
    script.src = 'https://accounts.google.com/gsi/client';
    script.async = true;
    script.onload = initGoogle;
    document.head.appendChild(script);
  }, []);

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    try {
      await AuthService.register({ fullName, username: email, password, role: 'ROLE_USER' });
      alert('✅ Registration successful! Please login.');
      navigate('/login');
    } catch (err: any) {
      setError(err.message || 'Registration failed');
      setIsLoading(false);
    }
  };

  const handleGoogleLogin = async (token: string) => {
    setIsLoading(true);
    try {
      await AuthService.loginWithGoogleIdToken(token);
      navigate('/bookings');
    } catch (err) {
      setError('Google login failed');
      setIsLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <div className="login-header">
          <h1>📝 Create Account</h1>
          <p>Join Smart Campus Ops Hub</p>
        </div>

        {error && <div className="error-message">{error}</div>}

        <form onSubmit={handleRegister}>
          <div className="form-group">
            <label className="form-label">Full Name</label>
            <input 
              type="text" 
              value={fullName} 
              onChange={e => setFullName(e.target.value)} 
              placeholder="John Doe" 
              required 
            />
          </div>
          <div className="form-group">
            <label className="form-label">Email Address</label>
            <input 
              type="email" 
              value={email} 
              onChange={e => setEmail(e.target.value)} 
              placeholder="email@example.com" 
              required 
            />
          </div>
          <div className="form-group">
            <label className="form-label">Password</label>
            <input 
              type="password" 
              value={password} 
              onChange={e => setPassword(e.target.value)} 
              placeholder="••••••••" 
              required 
            />
          </div>
          <button type="submit" className="btn-submit" disabled={isLoading}>
            {isLoading ? 'Creating account...' : 'Register'}
          </button>
        </form>

        <p className="auth-switch">
          Already have an account? <Link to="/login">Login here</Link>
        </p>
        <div className="divider"><span>OR</span></div>
        <div id="googleBtnReg" className="google-btn-container"></div>
      </div>
    </div>
  );
};

// frontend/src/app/features/auth/register.component.ts
import { Component, OnInit, OnDestroy, NgZone } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgIf } from '@angular/common';
import { AuthService } from './auth.service';
import { ToastService } from '../../core/toast.service';
import { Router, RouterLink } from '@angular/router';

declare var google: any;

@Component({
  standalone: true,
  selector: 'app-register',
  imports: [FormsModule, NgIf, RouterLink],
  template: `
    <div class="login-container">
      <div class="login-card">
        <div class="login-header">
          <h1>📝 Create Account</h1>
          <p>Join Smart Campus Ops Hub</p>
        </div>

        <div *ngIf="toast.message" [class]="'alert ' + (toast.message.includes('success') ? 'alert-success' : 'alert-error')">
          {{toast.message}}
        </div>

        <form (ngSubmit)="register()" #regForm="ngForm">
          <div class="form-group">
            <label class="form-label">Full Name</label>
            <input type="text" [(ngModel)]="fullName" name="fullName" placeholder="John Doe" required>
          </div>

          <div class="form-group">
            <label class="form-label">Email Address</label>
            <input type="email" [(ngModel)]="email" name="email" placeholder="email@example.com" required>
          </div>

          <div class="form-group">
            <label class="form-label">Password</label>
            <input type="password" [(ngModel)]="password" name="password" placeholder="••••••••" required>
          </div>

          <div class="button-group">
            <button type="submit" [disabled]="!regForm.valid || isLoading">
              {{isLoading ? 'Creating account...' : 'Register'}}
            </button>
          </div>
        </form>

        <p class="auth-switch">
          Already have an account? <a routerLink="/login">Login here</a>
        </p>

        <div class="divider"><span>OR</span></div>

        <div id="googleBtnReg" class="google-btn-container"></div>
      </div>
    </div>
  `,
  styles: [`
    .login-container { display: flex; justify-content: center; align-items: center; min-height: 60vh; }
    .login-card { background: white; border: 1px solid var(--gray-200); border-radius: 8px; padding: 40px; width: 100%; max-width: 500px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); }
    .login-header { text-align: center; margin-bottom: 32px; }
    .login-header h1 { margin: 0 0 8px 0; color: var(--primary); }
    .login-header p { color: var(--gray-500); margin: 0; }
    .button-group { display: flex; gap: 12px; margin-top: 24px; }
    .button-group button { flex: 1; }
    .auth-switch { text-align: center; margin-top: 16px; font-size: 14px; }
    .divider { margin: 24px 0; text-align: center; border-bottom: 1px solid var(--gray-200); line-height: 0.1em; }
    .divider span { background:#fff; padding:0 10px; color: var(--gray-500); font-size: 12px; }
    .google-btn-container { display: flex; justify-content: center; }
  `]
})
export class RegisterComponent implements OnInit, OnDestroy {
  fullName = '';
  email = '';
  password = '';
  isLoading = false;
  private googleInitInterval?: ReturnType<typeof setInterval>;

  constructor(
    public toast: ToastService,
    private auth: AuthService,
    private router: Router,
    private ngZone: NgZone
  ) {}

  ngOnInit() {
    const isLibraryLoaded = !!(window as any).google?.accounts?.id;
    
    if (!isLibraryLoaded) {
      const script = document.createElement('script');
      script.src = 'https://accounts.google.com/gsi/client';
      script.async = true;
      script.defer = true;
      script.onload = () => this.waitForButtonAndInit();
      document.head.appendChild(script);
    } else {
      this.waitForButtonAndInit();
    }
  }

  private waitForButtonAndInit() {
    this.googleInitInterval = setInterval(() => {
      const g = (window as any).google?.accounts?.id;
      const btn = document.getElementById('googleBtnReg');
      
      if (g && btn) {
        this.initGoogleAuth();
        clearInterval(this.googleInitInterval);
      }
    }, 100);
  }

  ngOnDestroy() {
    if (this.googleInitInterval) {
      clearInterval(this.googleInitInterval);
    }
  }

  initGoogleAuth() {
    if (typeof google !== 'undefined') {
      google.accounts.id.initialize({
        client_id: '725051219392-u8oac67c5dusdgb9ht9q3u683iss1lfl.apps.googleusercontent.com',
        callback: (response: any) => this.ngZone.run(() => this.handleGoogleLogin(response.credential)),
        auto_select: false,
        ux_mode: 'popup',
        context: 'signup'
      });
      google.accounts.id.renderButton(
        document.getElementById('googleBtnReg'),
        { theme: 'outline', size: 'large', width: 350, shape: 'rectangular', text: 'signup_with' }
      );
    }
  }

  register() {
    this.isLoading = true;
    const payload = {
      fullName: this.fullName,
      username: this.email,
      password: this.password,
      role: 'ROLE_USER'
    };
    this.auth.register(payload).subscribe({
      next: () => {
        this.isLoading = false;
        this.toast.show('✅ Registration successful! Please login.');
        console.log('Registration success - Navigating to /login');
        this.router.navigate(['/login']);
      },
      error: (e) => {
        this.isLoading = false;
        this.toast.show('❌ Registration failed: ' + (e?.error?.detail ?? e.message ?? 'Unknown error'));
      }
    });
  }

  handleGoogleLogin(token: string) {
    if (!token) {
      console.error('Google Auth returned an empty token.');
      return;
    }

    this.ngZone.run(() => {
      this.isLoading = true;
      this.auth.loginWithGoogleIdToken(token).subscribe({
        next: () => {
          this.isLoading = false;
          this.toast.show('✅ Login successful!');
          this.router.navigate(['/bookings']);
        },
        error: (e) => {
          this.isLoading = false;
          this.toast.show('❌ Login failed: ' + (e?.error?.detail ?? e.message ?? 'Unknown error'));
        }
      });
    });
  }
}
