// frontend/src/app/features/facility/facility-form/facility-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { FacilityService, Facility } from '../facility.service';

@Component({
  selector: 'app-facility-form',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './facility-form.component.html',
  styleUrls: ['./facility-form.component.css']
})
export class FacilityFormComponent implements OnInit {
  facility: Facility = {
    name: '',
    type: '',
    capacity: 0,
    location: '',
    availableFrom: '08:00:00',
    availableTo: '18:00:00',
    status: 'ACTIVE'
  };
  isEditMode = false;
  facilityId: number | null = null;
  isLoading = false;
  errorMessage = '';

  facilityTypes = ['LECTURE_HALL', 'LAB', 'MEETING_ROOM', 'EQUIPMENT'];
  statusOptions = ['ACTIVE', 'OUT_OF_SERVICE'];

  constructor(
    private facilityService: FacilityService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode = true;
      this.facilityId = +id;
      this.loadFacility();
    }
  }

  loadFacility(): void {
    this.isLoading = true;
    this.facilityService.getFacilityById(this.facilityId!).subscribe({
      next: (data) => {
        this.facility = data;
        this.isLoading = false;
      },
      error: (err) => {
        this.errorMessage = 'Failed to load facility';
        this.isLoading = false;
        console.error(err);
      }
    });
  }

  onSubmit(): void {
    if (!this.facility.name || !this.facility.type || !this.facility.location) {
      this.errorMessage = 'Please fill all required fields';
      return;
    }

    this.isLoading = true;
    
    if (this.isEditMode && this.facilityId) {
      this.facilityService.updateFacility(this.facilityId, this.facility).subscribe({
        next: () => {
          this.router.navigate(['/facilities']);
        },
        error: (err) => {
          this.errorMessage = 'Update failed';
          this.isLoading = false;
          console.error(err);
        }
      });
    } else {
      this.facilityService.createFacility(this.facility).subscribe({
        next: () => {
          this.router.navigate(['/facilities']);
        },
        error: (err) => {
          this.errorMessage = 'Create failed';
          this.isLoading = false;
          console.error(err);
        }
      });
    }
  }
}
<div class="form-container">
  <h2>{{ isEditMode ? 'Edit Facility' : 'Add New Facility' }}</h2>

  <div *ngIf="errorMessage" class="error-message">
    {{ errorMessage }}
  </div>

  <form (ngSubmit)="onSubmit()" class="facility-form">
    <div class="form-group">
      <label>Name *</label>
      <input type="text" [(ngModel)]="facility.name" name="name" required>
    </div>

    <div class="form-group">
      <label>Type *</label>
      <select [(ngModel)]="facility.type" name="type" required>
        <option value="">Select Type</option>
        <option *ngFor="let type of facilityTypes" [value]="type">{{ type }}</option>
      </select>
    </div>

    <div class="form-group">
      <label>Capacity</label>
      <input type="number" [(ngModel)]="facility.capacity" name="capacity">
    </div>

    <div class="form-group">
      <label>Location *</label>
      <input type="text" [(ngModel)]="facility.location" name="location" required>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label>Available From</label>
        <input type="time" [(ngModel)]="facility.availableFrom" name="availableFrom">
      </div>

      <div class="form-group">
        <label>Available To</label>
        <input type="time" [(ngModel)]="facility.availableTo" name="availableTo">
      </div>
    </div>

    <div class="form-group">
      <label>Status</label>
      <select [(ngModel)]="facility.status" name="status">
        <option *ngFor="let status of statusOptions" [value]="status">{{ status }}</option>
      </select>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn-primary" [disabled]="isLoading">
        {{ isLoading ? 'Saving...' : (isEditMode ? 'Update' : 'Create') }}
      </button>
      <button type="button" class="btn-secondary" (click)="router.navigate(['/facilities'])">
        Cancel
      </button>
    </div>
  </form>
</div>

// frontend/src/app/features/facility/facility-form/facility-form.component.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { API_BASE } from '../../../core/api';

export const FacilityFormComponent = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEditMode = !!id;

  const [facility, setFacility] = useState({
    name: '',
    type: 'LECTURE_HALL',
    capacity: 0,
    location: '',
    status: 'ACTIVE'
  });
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (isEditMode) {
      fetch(`${API_BASE}/facilities/${id}`)
        .then(res => res.json())
        .then(data => setFacility(data))
        .catch(err => console.error('Load failed', err));
    }
  }, [id, isEditMode]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const url = isEditMode ? `${API_BASE}/facilities/${id}` : `${API_BASE}/facilities`;
      const method = isEditMode ? 'PUT' : 'POST';
      
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(facility)
      });

      if (res.ok) {
        navigate('/facilities');
      }
    } catch (err) {
      alert('Operation failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ padding: '40px', maxWidth: '600px' }}>
      <div className="card">
        <h2>{isEditMode ? '✏️ Edit Facility' : '🏢 Add New Facility'}</h2>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label className="form-label">Facility Name</label>
            <input 
              value={facility.name} 
              onChange={e => setFacility({...facility, name: e.target.value})} 
              required 
            />
          </div>
          <div className="form-group">
            <label className="form-label">Type</label>
            <select 
              value={facility.type} 
              onChange={e => setFacility({...facility, type: e.target.value})}
            >
              <option value="LECTURE_HALL">Lecture Hall</option>
              <option value="LAB">Lab</option>
              <option value="MEETING_ROOM">Meeting Room</option>
              <option value="EQUIPMENT">Equipment</option>
            </select>
          </div>
          <div className="form-group">
            <label className="form-label">Location</label>
            <input 
              value={facility.location} 
              onChange={e => setFacility({...facility, location: e.target.value})} 
              required 
            />
          </div>
          <div className="form-group">
            <label className="form-label">Capacity</label>
            <input 
              type="number" 
              value={facility.capacity} 
              onChange={e => setFacility({...facility, capacity: parseInt(e.target.value)})} 
              required 
            />
          </div>
          <div style={{ display: 'flex', gap: '10px', marginTop: '20px' }}>
            <button type="submit" className="btn-submit" disabled={loading}>
              {loading ? 'Saving...' : 'Save Facility'}
            </button>
            <button type="button" className="secondary" onClick={() => navigate('/facilities')}>
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
