// frontend/src/components/FacilityForm.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { facilityService, Facility } from '../services/facility.service';
import './FacilityForm.css';

const FacilityForm: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = !!id;

  const [facility, setFacility] = useState<Facility>({
    name: '',
    type: '',
    capacity: 0,
    location: '',
    availableTo: '',
    status: 'ACTIVE'
  });
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  const facilityTypes = ['LECTURE_HALL', 'LAB', 'MEETING_ROOM', 'EQUIPMENT'];
  const statusOptions = ['ACTIVE', 'OUT_OF_SERVICE'];

  useEffect(() => {
    if (isEditMode && id) {
      loadFacility();
    }
  }, [id, isEditMode]);

  const loadFacility = () => {
    setIsLoading(true);
    facilityService.getById(id!).then((response) => {
      setFacility(response.data);
      setIsLoading(false);
    }).catch(() => {
      setErrorMessage('Failed to load facility');
      setIsLoading(false);
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setErrorMessage('');
    setSuccessMessage('');

    // Validation
    if (!facility.name.trim()) {
      setErrorMessage('Facility name is required');
      setIsLoading(false);
      return;
    }
    if (!facility.type) {
      setErrorMessage('Facility type is required');
      setIsLoading(false);
      return;
    }
    if (!facility.location.trim()) {
      setErrorMessage('Location is required');
      setIsLoading(false);
      return;
    }

    if (isEditMode && id) {
      facilityService.update(id, facility).then(() => {
        setSuccessMessage('Facility updated successfully!');
        setTimeout(() => navigate('/facilities'), 1500);
      }).catch((err) => {
        setErrorMessage(err.response?.data?.message || 'Update failed');
        setIsLoading(false);
      });
    } else {
      facilityService.create(facility).then(() => {
        setSuccessMessage('Facility created successfully!');
        setTimeout(() => navigate('/facilities'), 1500);
      }).catch((err) => {
        setErrorMessage(err.response?.data?.message || 'Create failed');
        setIsLoading(false);
      });
    }
  };

  return (
    <div className="form-container">
      <div className="form-card">
        <h2>{isEditMode ? '✏️ Edit Facility' : '➕ Add New Facility'}</h2>
        <p>{isEditMode ? 'Update facility information' : 'Fill in the details to add a new facility'}</p>
        
        {errorMessage && <div className="error-message">{errorMessage}</div>}
        {successMessage && <div className="success-message">{successMessage}</div>}
        
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>Facility Name <span className="required">*</span></label>
            <input 
              type="text" 
              value={facility.name} 
              onChange={(e) => setFacility({...facility, name: e.target.value})} 
              placeholder="e.g., Hall A, Computer Lab 1"
              required 
            />
          </div>

          <div className="form-group">
            <label>Facility Type <span className="required">*</span></label>
            <select value={facility.type} onChange={(e) => setFacility({...facility, type: e.target.value})} required>
              <option value="">Select Facility Type</option>
              {facilityTypes.map(type => (
                <option key={type} value={type}>
                  {type === 'LECTURE_HALL' ? '📚 Lecture Hall' : 
                   type === 'LAB' ? '💻 Lab' : 
                   type === 'MEETING_ROOM' ? '🤝 Meeting Room' : 
                   '📷 Equipment'}
                </option>
              ))}
            </select>
          </div>

          <div className="form-row">
            <div className="form-group">
              <label>Capacity</label>
              <input 
                type="number" 
                value={facility.capacity || ''} 
                onChange={(e) => setFacility({...facility, capacity: parseInt(e.target.value) || 0})} 
                placeholder="Number of people/items"
                min="1"
              />
            </div>

            <div className="form-group">
              <label>Available To (Time)</label>
              <input 
                type="time" 
                value={facility.availableTo} 
                onChange={(e) => setFacility({...facility, availableTo: e.target.value})} 
              />
            </div>
          </div>

          <div className="form-group">
            <label>Location <span className="required">*</span></label>
            <input 
              type="text" 
              value={facility.location} 
              onChange={(e) => setFacility({...facility, location: e.target.value})} 
              placeholder="e.g., Building 1, Floor 2"
              required 
            />
          </div>

          <div className="form-group">
            <label>Status</label>
            <select value={facility.status} onChange={(e) => setFacility({...facility, status: e.target.value})}>
              {statusOptions.map(status => (
                <option key={status} value={status}>
                  {status === 'ACTIVE' ? '🟢 Active' : '🔴 Out of Service'}
                </option>
              ))}
            </select>
          </div>

          <div className="form-actions">
            <button type="submit" className="btn-submit" disabled={isLoading}>
              {isLoading ? 'Saving...' : (isEditMode ? '✏️ Update Facility' : '➕ Create Facility')}
            </button>
            <button type="button" className="btn-cancel" onClick={() => navigate('/facilities')}>
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default FacilityForm;

// frontend/src/app/features/facility/facility-form/facility-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { FacilityService, Facility } from '../facility.service';

@Component({
  selector: 'app-facility-form',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './facility-form.component.html',
  styleUrls: ['./facility-form.component.css']
})
export class FacilityFormComponent implements OnInit {
  facility: Facility = {
    name: '',
    type: '',
    capacity: 0,
    location: '',
    availableFrom: '08:00:00',
    availableTo: '18:00:00',
    status: 'ACTIVE'
  };
  isEditMode = false;
  facilityId: number | null = null;
  isLoading = false;
  errorMessage = '';

  facilityTypes = ['LECTURE_HALL', 'LAB', 'MEETING_ROOM', 'EQUIPMENT'];
  statusOptions = ['ACTIVE', 'OUT_OF_SERVICE'];

  constructor(
    private facilityService: FacilityService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode = true;
      this.facilityId = +id;
      this.loadFacility();
    }
  }

  loadFacility(): void {
    this.isLoading = true;
    this.facilityService.getFacilityById(this.facilityId!).subscribe({
      next: (data) => {
        this.facility = data;
        this.isLoading = false;
      },
      error: (err) => {
        this.errorMessage = 'Failed to load facility';
        this.isLoading = false;
        console.error(err);
      }
    });
  }

  onSubmit(): void {
    if (!this.facility.name || !this.facility.type || !this.facility.location) {
      this.errorMessage = 'Please fill all required fields';
      return;
    }

    this.isLoading = true;
    
    if (this.isEditMode && this.facilityId) {
      this.facilityService.updateFacility(this.facilityId, this.facility).subscribe({
        next: () => {
          this.router.navigate(['/facilities']);
        },
        error: (err) => {
          this.errorMessage = 'Update failed';
          this.isLoading = false;
          console.error(err);
        }
      });
    } else {
      this.facilityService.createFacility(this.facility).subscribe({
        next: () => {
          this.router.navigate(['/facilities']);
        },
        error: (err) => {
          this.errorMessage = 'Create failed';
          this.isLoading = false;
          console.error(err);
        }
      });
    }
  }
}
<div class="form-container">
  <h2>{{ isEditMode ? 'Edit Facility' : 'Add New Facility' }}</h2>

  <div *ngIf="errorMessage" class="error-message">
    {{ errorMessage }}
  </div>

  <form (ngSubmit)="onSubmit()" class="facility-form">
    <div class="form-group">
      <label>Name *</label>
      <input type="text" [(ngModel)]="facility.name" name="name" required>
    </div>

    <div class="form-group">
      <label>Type *</label>
      <select [(ngModel)]="facility.type" name="type" required>
        <option value="">Select Type</option>
        <option *ngFor="let type of facilityTypes" [value]="type">{{ type }}</option>
      </select>
    </div>

    <div class="form-group">
      <label>Capacity</label>
      <input type="number" [(ngModel)]="facility.capacity" name="capacity">
    </div>

    <div class="form-group">
      <label>Location *</label>
      <input type="text" [(ngModel)]="facility.location" name="location" required>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label>Available From</label>
        <input type="time" [(ngModel)]="facility.availableFrom" name="availableFrom">
      </div>

      <div class="form-group">
        <label>Available To</label>
        <input type="time" [(ngModel)]="facility.availableTo" name="availableTo">
      </div>
    </div>

    <div class="form-group">
      <label>Status</label>
      <select [(ngModel)]="facility.status" name="status">
        <option *ngFor="let status of statusOptions" [value]="status">{{ status }}</option>
      </select>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn-primary" [disabled]="isLoading">
        {{ isLoading ? 'Saving...' : (isEditMode ? 'Update' : 'Create') }}
      </button>
      <button type="button" class="btn-secondary" (click)="router.navigate(['/facilities'])">
        Cancel
      </button>
    </div>
  </form>
</div>
