// frontend/src/components/AdminDashboard.tsx
import React, { useState, useEffect } from 'react';
import { facilityService, Facility } from '../services/facility.service';
import './AdminDashboard.css';

const AdminDashboard: React.FC = () => {
  const [facilities, setFacilities] = useState<Facility[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    facilityService.getAll()
      .then((response) => {
        setFacilities(response.data);
        setIsLoading(false);
      })
      .catch(() => setIsLoading(false));
  }, []);

  const totalFacilities = facilities.length;
  const activeFacilities = facilities.filter(f => f.status === 'ACTIVE').length;
  const inactiveFacilities = facilities.filter(f => f.status === 'OUT_OF_SERVICE').length;
  const utilization = totalFacilities > 0 ? ((activeFacilities / totalFacilities) * 100).toFixed(0) : 0;

  // Group by type
  const typeCount: { [key: string]: number } = {};
  facilities.forEach(f => {
    typeCount[f.type] = (typeCount[f.type] || 0) + 1;
  });

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <h1>📊 Admin Dashboard</h1>
        <p>Overview of campus facilities</p>
      </div>

      {isLoading ? (
        <div className="loading">⏳ Loading dashboard...</div>
      ) : (
        <>
          {/* Stats Cards */}
          <div className="stats-grid">
            <div className="stat-card">
              <div className="stat-icon">🏢</div>
              <div className="stat-value">{totalFacilities}</div>
              <div className="stat-label">Total Facilities</div>
            </div>
            <div className="stat-card success">
              <div className="stat-icon">✅</div>
              <div className="stat-value">{activeFacilities}</div>
              <div className="stat-label">Active</div>
            </div>
            <div className="stat-card warning">
              <div className="stat-icon">⚠️</div>
              <div className="stat-value">{inactiveFacilities}</div>
              <div className="stat-label">Inactive</div>
            </div>
            <div className="stat-card info">
              <div className="stat-icon">📊</div>
              <div className="stat-value">{utilization}%</div>
              <div className="stat-label">Utilization</div>
            </div>
          </div>

          {/* Facilities by Type Chart */}
          <div className="chart-card">
            <h3>📊 Facilities by Type</h3>
            <div className="type-list">
              {Object.entries(typeCount).map(([type, count]) => (
                <div key={type} className="type-item">
                  <span className="type-name">{type}</span>
                  <div className="bar-container">
                    <div className="bar" style={{ width: `${(count / totalFacilities) * 100}%` }}></div>
                  </div>
                  <span className="type-count">{count}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Recent Facilities Table */}
          <div className="recent-card">
            <h3>📋 Recent Facilities</h3>
            <table className="recent-table">
              <thead>
                <tr key="header">
                  <th>Name</th>
                  <th>Type</th>
                  <th>Location</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {facilities.slice(0, 5).map((facility) => (
                  <tr key={facility.id}>
                    <td>{facility.name}</td>
                    <td>{facility.type}</td>
                    <td>{facility.location}</td>
                    <td className="status-cell">
                      <span className={facility.status === 'ACTIVE' ? 'status-active' : 'status-inactive'}>
                        {facility.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
};

export default AdminDashboard;

// frontend/src/app/features/admin/admin-dashboard/admin-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FacilityService, Facility } from '../../facility/facility.service';
import { AuthService } from '../../../core/auth.service';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './admin-dashboard.component.html',
  styleUrls: ['./admin-dashboard.component.css']
})
export class AdminDashboardComponent implements OnInit {
  facilities: Facility[] = [];
  isLoading = true;
  errorMessage = '';

  // Stats
  totalFacilities = 0;
  activeFacilities = 0;
  inactiveFacilities = 0;
  totalCapacity = 0;

  // Charts data
  facilityTypes: { type: string; count: number }[] = [];
  statusDistribution: { status: string; count: number }[] = [];

  constructor(
    private facilityService: FacilityService,
    public authService: AuthService
  ) {}

  ngOnInit(): void {
    if (this.authService.isAdmin()) {
      this.loadData();
    }
  }

  loadData(): void {
    this.isLoading = true;
    this.facilityService.getAllFacilities().subscribe({
      next: (facilities) => {
        this.facilities = facilities;
        this.calculateStats();
        this.isLoading = false;
      },
      error: (err) => {
        this.errorMessage = 'Failed to load dashboard data';
        this.isLoading = false;
        console.error(err);
      }
    });
  }

  calculateStats(): void {
    this.totalFacilities = this.facilities.length;
    this.activeFacilities = this.facilities.filter(f => f.status === 'ACTIVE').length;
    this.inactiveFacilities = this.facilities.filter(f => f.status === 'OUT_OF_SERVICE').length;
    this.totalCapacity = this.facilities.reduce((sum, f) => sum + (f.capacity || 0), 0);

    // Group by type
    const typeMap = new Map<string, number>();
    this.facilities.forEach(f => {
      typeMap.set(f.type, (typeMap.get(f.type) || 0) + 1);
    });
    this.facilityTypes = Array.from(typeMap.entries()).map(([type, count]) => ({ type, count }));

    // Status distribution
    const statusMap = new Map<string, number>();
    this.facilities.forEach(f => {
      statusMap.set(f.status, (statusMap.get(f.status) || 0) + 1);
    });
    this.statusDistribution = Array.from(statusMap.entries()).map(([status, count]) => ({ status, count }));
  }
}
<!-- Only visible to Admin -->
<div *ngIf="!authService.isAdmin()" class="access-denied">
  <h2>🚫 Access Denied</h2>
  <p>You don't have permission to view this page.</p>
</div>

<div *ngIf="authService.isAdmin()" class="dashboard-container">
  <!-- Header -->
  <div class="dashboard-header">
    <h1>📊 Admin Dashboard</h1>
    <p>Welcome back, <strong>{{ authService.getCurrentUser()?.fullName }}</strong></p>
  </div>

  <!-- Loading -->
  <div *ngIf="isLoading" class="loading">
    <div class="spinner"></div>
    <p>Loading dashboard data...</p>
  </div>

  <!-- Error -->
  <div *ngIf="errorMessage" class="error-message">
    {{ errorMessage }}
  </div>

  <!-- Dashboard Content -->
  <div *ngIf="!isLoading && !errorMessage" class="dashboard-content">
    
    <!-- Stats Cards -->
    <div class="stats-grid">
      <div class="stat-card primary">
        <div class="stat-icon">🏢</div>
        <div class="stat-value">{{ totalFacilities }}</div>
        <div class="stat-label">Total Facilities</div>
      </div>
      <div class="stat-card success">
        <div class="stat-icon">✅</div>
        <div class="stat-value">{{ activeFacilities }}</div>
        <div class="stat-label">Active Facilities</div>
      </div>
      <div class="stat-card danger">
        <div class="stat-icon">⚠️</div>
        <div class="stat-value">{{ inactiveFacilities }}</div>
        <div class="stat-label">Inactive Facilities</div>
      </div>
      <div class="stat-card info">
        <div class="stat-icon">💺</div>
        <div class="stat-value">{{ totalCapacity }}</div>
        <div class="stat-label">Total Capacity</div>
      </div>
    </div>

    <!-- Charts Row -->
    <div class="charts-row">
      <!-- Facility Types Chart -->
      <div class="chart-card">
        <h3>📊 Facilities by Type</h3>
        <div class="type-list">
          <div *ngFor="let item of facilityTypes" class="type-item">
            <span class="type-name">{{ item.type }}</span>
            <div class="type-bar-container">
              <div class="type-bar" [style.width.%]="(item.count / totalFacilities) * 100"></div>
            </div>
            <span class="type-count">{{ item.count }}</span>
          </div>
        </div>
      </div>

      <!-- Status Distribution -->
      <div class="chart-card">
        <h3>📈 Status Distribution</h3>
        <div class="status-list">
          <div *ngFor="let item of statusDistribution" class="status-item">
            <span class="status-name" [class]="item.status === 'ACTIVE' ? 'status-active' : 'status-inactive'">
              {{ item.status === 'ACTIVE' ? '🟢 ACTIVE' : '🔴 OUT OF SERVICE' }}
            </span>
            <div class="status-bar-container">
              <div class="status-bar" [class.active]="item.status === 'ACTIVE'" [style.width.%]="(item.count / totalFacilities) * 100"></div>
            </div>
            <span class="status-count">{{ item.count }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Recent Facilities Table -->
    <div class="chart-card full-width">
      <h3>📋 Recent Facilities</h3>
      <table class="facility-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Type</th>
            <th>Capacity</th>
            <th>Location</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let facility of facilities.slice(0, 5)">
            <td>{{ facility.id | slice:0:8 }}...</td>
            <td>{{ facility.name }}</td>
            <td>{{ facility.type }}</td>
            <td>{{ facility.capacity }}</td>
            <td>{{ facility.location }}</td>
            <td>
              <span [class]="facility.status === 'ACTIVE' ? 'badge-active' : 'badge-inactive'">
                {{ facility.status }}
              </span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
